version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies..."
      - pip install opensearchpy -t lib
      - pip install requests_aws4auth -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - mkdir build
      - mv deployment_package.zip build/deployment_package_index_photos.zip
      - cp build/deployment_package_index_photos.zip build/deployment_package_search_photos.zip
      - mv LF1.py lambda_function.py
      - zip -g build/deployment_package_index_photos.zip lambda_function.py
      - mv LF2.py lambda_function.py
      - zip -g build/deployment_package_search_photos.zip lambda_function.py

      - echo "Deploying lambda Function..."
      - cd build
      - aws lambda update-function-code --function-name index-test --zip-file fileb://deployment_package_index_photos.zip
      - aws lambda update-function-code --function-name search-test --zip-file fileb://deployment_package_search_photos.zip
      - echo "DONE!!"


artifacts:
  files:
    - 'build/*'
